im_site/im_site/urls.py
from django.conf import settings
from django.conf.urls.static import static

"""im_site URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView


urlpatterns = [
    path('favicon.ico',RedirectView.as_view(url=settings.STATIC_URL + 'favicon.ico')),
    path('imapp/', include('imapp.urls')),
    path('admin/',admin.site.urls ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

im_site/imapp/urls.py
from django.urls import path
from . import views

app_name = 'imapp'
urlpatterns = [
    # ex: /imapp/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /imapp/register, /imapp/deregister ...
    path('register/', views.register.as_view(), name='register'),
    path('log/', views.LogView.as_view(), name='log'),
    path('sclog/', views.scLogView.as_view(), name='sclog'),
    # ex: /imapp/log/D01/
    path('log/<str:sam_site>/', views.loglog, name='loglog'),
    # unregister
    path('unregister/index/<int:mode_id>/', views.UnregisterIndexView.as_view(), name='unregister_index'),
    path('unregister/confirm/<int:mode_id>/', views.UnregisterConfirmView.as_view(), name='unregister_confirm'),
    path('unregister/run/<int:mode_id>', views.run_unregister, name='unregister_run'),
]

im_site/imapp/models.py
import datetime

from django.db import models
from django.utils import timezone
from django import forms


class ModelInfo(models.Model):
    model_id = models.AutoField('モデルID',
                                primary_key=True)
    pc_or_display = models.CharField(
        '区分', max_length=100, choices=(('pc', 'PC'), ('display', 'ディスプレイ'),))
    desk_or_lap = models.CharField('種類', max_length=100,
                                   choices=(('desktop', 'デスクトップPC'), ('laptop', 'ノートPC'),), null=True)
    model_name = models.CharField('モデル名', max_length=100)
    maker = models.CharField('メーカー', max_length=100)
    release_date = models.DateField('発売日')

    class Meta:
        unique_together = ('pc_or_display', 'model_name',
                           'maker', 'release_date',)
        verbose_name = "モデル"  # model-name on admin/imapp/$MODEL
        verbose_name_plural = "モデル"  # model-name on admin/imapp

    def __str__(self):
        return str(self.model_name)


class DisplayInfo(models.Model):
    model_id = models.OneToOneField(
        ModelInfo,
        related_name="related_model_id",
        on_delete=models.CASCADE, primary_key=True)
    inch = models.FloatField('インチ', default=24.0)

    class Meta:
        verbose_name = "ディスプレイ情報"
        verbose_name_plural = "ディスプレイ情報"

    def __str__(self):
        return str(self.inch)


class Equipment(models.Model):
    sam = models.CharField('SAM', max_length=100, primary_key=True)
    pc_or_display = models.CharField('区分', max_length=100, choices=(
        ('pc', 'PC'),
        ('display', 'ディスプレイ'),))
    purchase = models.DateField('購入日')
    warranty = models.DateField('保証期限')
    note = models.TextField('備考', blank=True)
    model_id = models.ForeignKey(ModelInfo, on_delete=models.PROTECT)

    class Meta:
        verbose_name = "備品 (PC)"
        verbose_name_plural = "備品 (PC)"

    def __str__(self):
        return str(self.sam)


class OsId(models.Model):
    os_id = models.AutoField('OSID', primary_key=True)
    os = models.CharField('OS', max_length=100, unique=True)

    class Meta:
        verbose_name = "OS"
        verbose_name_plural = "OS"

    def __str__(self):
        return str(self.os)


class CpuId(models.Model):
    cpu_id = models.AutoField('CPU',
                              primary_key=True)
    cpu = models.CharField('CPU', max_length=100, unique=True)

    class Meta:
        verbose_name = "CPU"
        verbose_name_plural = "CPU"

    def __str__(self):
        return str(self.cpu)


class DriveId(models.Model):
    drive_id = models.AutoField('ドライブID', primary_key=True)
    drive = models.CharField('ドライブ', max_length=100, unique=True)

    class Meta:
        verbose_name = "ドライブ"
        verbose_name_plural = "ドライブ"

    def __str__(self):
        return str(self.drive)

class MemoryId(models.Model):
    memory_id = models.AutoField('メモリID', primary_key=True)
    memory = models.CharField('メモリ', max_length=100, unique=True)

    class Meta:
        verbose_name = "メモリ"
        verbose_name_plural = "メモリ"

    def __str__(self):
        return str(self.memory)

class PcEquipment(models.Model):
    sam = models.OneToOneField(
        Equipment,
        related_name="related_sam_id",
        on_delete=models.CASCADE, primary_key=True)
    os_id = models.ForeignKey(OsId, on_delete=models.PROTECT)
    cpu_id = models.ForeignKey(CpuId,
                               on_delete=models.PROTECT)
    drive_id = models.ForeignKey(DriveId, on_delete=models.PROTECT)
    memory_id = models.ForeignKey(MemoryId, on_delete=models.PROTECT)

    class Meta:
        verbose_name = "PC備品"
        verbose_name_plural = "PC備品"

    def __str__(self):
        return str(self.sam)


class User(models.Model):
    YEAR_CHOICES = []
    for r in range(2006, (datetime.datetime.now().year+1)):
        YEAR_CHOICES.append((r, r))
    YEAR_CHOICES.sort(reverse=True)
    user_id = models.AutoField('利用者ID', primary_key=True)
    username = models.CharField('利用者名', max_length=100)
    assigned_year = models.IntegerField(
        '配属年度', choices=YEAR_CHOICES, default=datetime.datetime.now().year)
    is_affiliated = models.BooleanField('現役？', default=True)

    class Meta:
        unique_together = ('username', 'assigned_year',)
        verbose_name = "利用者"
        verbose_name_plural = "利用者"

    def judge_affiliation(self):
        return self.is_affiliated

    judge_affiliation.admin_order_field = 'is_affiliated'
    judge_affiliation.boolean = True
    judge_affiliation.short_description = "現役?????"

    def __str__(self):
        return str(self.username) + " (" + str(self.assigned_year) + "年配属) "


class Log(models.Model):
    """
    'id' is automatically made and set as a primary key.
    """
    sam = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    begin_date = models.DateField('使用開始日')
    user_id = models.ForeignKey(User,
                                on_delete=models.CASCADE)

    class Meta:
        unique_together = ('sam', 'begin_date', 'user_id',)
        verbose_name = "ログ"
        verbose_name_plural = "ログ ⚠基本的に使用しないこと⚠"

    def __str__(self):
        return "(" + str(self.sam) + ", " + str(self.user_id.username) + ", " + str(self.begin_date) + ")"

im_site/imapp/forms.py
from django import forms

im_site/imapp/views.py
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from .models import ModelInfo, Equipment, User, PcEquipment, Log
from django.db import connection
from django.template import loader
from collections import defaultdict
from datetime import datetime
from django.shortcuts import render, redirect
from django.http import Http404
from django.urls import reverse

NOT_ASSIGNED_ID = 1
TO_BE_SCRAPPED_ID = 2
SCRAPPED_ID = 3

ID_MODE = {NOT_ASSIGNED_ID, TO_BE_SCRAPPED_ID, SCRAPPED_ID}


class RegisterBaseInfo:
    def __init__(self, username, userid, year, desktop, laptop, displays):
        self.username = username
        self.userid = userid
        self.assignedyear = year
        self.desktop = desktop
        self.laptop = laptop
        self.displays = displays

    def __str__(self):
        return "in RegisterBaseInfo class(debug on __str__): " + str(self.username) + ", " + str(
            self.userid) + ", " + str(self.desktop) + ", " + str(self.laptop) + ", " + str(self.displays)


class register(generic.ListView):
    """
    in registering user&sam to log
    """
    template_name = 'imapp/register.html'

    NO_DEFAULT_SAM = "該当なし"
    DISPOSAL_ID = [TO_BE_SCRAPPED_ID, SCRAPPED_ID]  # disposal or will dispose
    # not assigned or disposal or will dispose
    NO_USE_ID = [NOT_ASSIGNED_ID, TO_BE_SCRAPPED_ID, SCRAPPED_ID]

    def __init__(self):
        self.SendContentsSave = []

    def GetValidSamAndUsersSam(self, SendContents, DesktopSamTable, LaptopSamTable, DisplaySamTable):
        """
        Requirement: A and B don't exist such as A.sam == B.sum ∧ A.begin_date == B.begin_date is in LOG
        {users}, {user-desktop-sam, {vaild-desktop-sam}}, 
        {user-laptop-sam, {vaild-laptop-sam}}, {user-displaysam1/2, {valid-display-sam}}

        """
        cursor = connection.cursor()
        cursor.execute("""SELECT sam_id,user_id_id FROM (SELECT A.sam_id, 
        A.user_id_id FROM imapp_log AS A INNER JOIN 
        (SELECT sam_id, MAX(begin_date) AS MaxDate 
        FROM `imapp_log` GROUP BY sam_id) AS B
        ON A.sam_id = B.sam_id AND A.begin_date = B.MaxDate ) as C 
        INNER JOIN imapp_user ON C.user_id_id = imapp_user.user_id""")
        sam_userid_rows = cursor.fetchall()

        # No valid ID
        NoValidSumTable = []
        userid_sam_dfdict = defaultdict(list)
        for sam, userid in sam_userid_rows:
            if userid not in self.DISPOSAL_ID:
                userid_sam_dfdict[userid].append(sam)
            else:
                NoValidSumTable.append(sam)

        # display valid ID
        DisplaySamTable.clear()

        for dic in Equipment.objects.all().filter(pc_or_display="display").values():
            if dic["sam"] not in NoValidSumTable:
                DisplaySamTable.append(dic["sam"])
        DisplaySamTable.append(self.NO_DEFAULT_SAM)

        # Desktop valid ID
        DesktopSamTable.clear()

        desktop_dicts = ModelInfo.objects.all().filter(desk_or_lap="desktop").values()
        desktop_model_ids = [id_dict['model_id'] for id_dict in desktop_dicts]

        for equip in Equipment.objects.all().values():
            if equip["model_id_id"] in desktop_model_ids:
                if equip["sam"] not in NoValidSumTable:
                    DesktopSamTable.append(equip["sam"])
        DesktopSamTable.append(self.NO_DEFAULT_SAM)

        # Laptop valid ID
        LaptopSamTable.clear()

        laptop_dicts = ModelInfo.objects.all().filter(desk_or_lap="laptop").values()
        laptop_model_ids = [id_dict['model_id'] for id_dict in laptop_dicts]

        for equip in Equipment.objects.all().values():
            if equip["model_id_id"] in laptop_model_ids:
                if equip["sam"] not in NoValidSumTable:
                    LaptopSamTable.append(equip["sam"])
        LaptopSamTable.append(self.NO_DEFAULT_SAM)

        userid_sam_dict = dict(userid_sam_dfdict)  # defaultdict to dict

        SendContents.clear()
        for userdata in User.objects.all().values():
            username = userdata["username"]
            userid = userdata["user_id"]
            user_assignedyeser = userdata["assigned_year"]
            if userid in self.NO_USE_ID:
                continue
            if userdata["is_affiliated"] == False:
                continue

            UserSamSet = []
            if userid in userid_sam_dict.keys():
                UserSamSet = userid_sam_dict[userid]

            desktopsam = ""  # if cond assignment
            laptopsam = ""
            displaysams = []
            for sam in UserSamSet:
                if sam in DesktopSamTable:
                    desktopsam = sam
                elif sam in LaptopSamTable:
                    laptopsam = sam
                elif sam in DisplaySamTable:
                    displaysams.append(sam)

            # if a person doesn't have sam -> person.sth.sam=NO_DEFAULT_SAM
            if len(desktopsam) < 1:
                desktopsam = self.NO_DEFAULT_SAM
            if len(laptopsam) < 1:
                laptopsam = self.NO_DEFAULT_SAM
            for i in range(2 - len(displaysams)):
                displaysams.append(self.NO_DEFAULT_SAM)
            SendContents.append(RegisterBaseInfo(
                username, userid, user_assignedyeser, desktopsam, laptopsam, displaysams))

    def validsetting(self):
        pass

    def post(self, request, *args, **kwargs):

        post_data = request.POST

        post_id = int(post_data["userid"])
        d =  post_data["desktop-pulldown"]
        l =  post_data["laptop-pulldown"]
        d1 = post_data["display1-pulldown"]
        d2 = post_data["display2-pulldown"]


        # get pre information
        SendContents = []
        DesktopSamTable = []
        LapTopSamTable = []
        DisplaySamTable = []
        self.GetValidSamAndUsersSam(SendContents, DesktopSamTable,
                              LapTopSamTable, DisplaySamTable)


        # get who change sam
        postinfo = RegisterBaseInfo("", post_id, 0, d, l, [d1, d2])
        preinfo = postinfo
        for pre in SendContents:
            if pre.userid == post_id:
                preinfo = pre

        # get pre/change infomation ↓
        predisp1 = preinfo.displays[0]
        predisp2 = preinfo.displays[1]

        # desktop
        class OldAndNew():
            def __init__(self, oldsam, newsam):
                self.newsam = newsam
                self.oldsam = oldsam

        checksams = []
        if preinfo.desktop != postinfo.desktop:
            checksams.append(OldAndNew(preinfo.desktop, postinfo.desktop))

        # laptop
        if preinfo.laptop != postinfo.laptop:
            checksams.append(OldAndNew(preinfo.laptop, postinfo.laptop))

        # display: 2displays -> check algorithm
        deletelist_old = []
        deletelist_new = []
        boolenlist_old = [False for a in preinfo.displays]
        boolenlist_new = [False for a in postinfo.displays]
        for i, newsam in enumerate(postinfo.displays):
            for j, oldsam in enumerate(preinfo.displays):
                if boolenlist_new[i] == False and boolenlist_old[j] == False and newsam == oldsam:
                    deletelist_old.append(oldsam)
                    deletelist_new.append(newsam)
                    boolenlist_old[j] = True
                    boolenlist_new[i] = True

        for oldsam in deletelist_old:
            preinfo.displays.remove(oldsam)
        for newsam in deletelist_new:
            postinfo.displays.remove(newsam)

        assert len(postinfo.displays) == len(
            preinfo.displays), "the size of preinfo.displays is not postinfo.displays, ><"
        for (oldsam, newsam) in zip(preinfo.displays, postinfo.displays):
            checksams.append(OldAndNew(oldsam, newsam))


        """
        old sam -> no_assinnment
        new sam -> person
        """
        ## old sam to LOG
        # if same sam and begin_date in LOG, delete it
        for obj in checksams:
            oldsam = obj.oldsam
            Logsset = Log.objects.all().filter(sam=oldsam, begin_date=datetime.now())
            # if nothing is target, none happens
            Logsset.delete()

        for obj in checksams:
            if obj.oldsam == self.NO_DEFAULT_SAM:
                continue
            insert_query = Log(
                sam=Equipment.objects.get(sam=obj.oldsam),
                begin_date=datetime.now(),
                user_id=User.objects.get(user_id=NOT_ASSIGNED_ID)
            )
            insert_query.save()


        # delete same date and sam
        for obj in checksams:
            if obj.newsam == self.NO_DEFAULT_SAM:
                continue
            newsam = obj.newsam
            Logsset = Log.objects.all().filter(sam=newsam, begin_date=datetime.now())
            Logsset.delete() # if nothing is target, none happens

        # new data to LOG
        for obj in checksams:
            if obj.newsam == self.NO_DEFAULT_SAM:
                continue
            insert_query = Log(
                sam=Equipment.objects.get(sam=obj.newsam),
                begin_date=datetime.now(),
                user_id=User.objects.get(user_id=postinfo.userid)
            )
            insert_query.save()

        class SamChangeInfo:  # insert only diff data
            def __init__(self, id, de, l, d1, d2, change=False, deskch=False, lapch=False, dispch=False):
                self.id = id
                self.desktop = de
                self.laptop = l
                self.display = [d1, d2]
                self.change = change
                self.desktopchange = deskch
                self.laptopchange = lapch
                self.displaychange = dispch

        # diff check(worst...)
        cnt = 0
        chflag = False
        deskflag = False
        lapflag = False
        dispflag = False
        if preinfo.desktop == postinfo.desktop:
            cnt += 1
        else:
            deskflag = True

im_site/imapp/templates/imapp/unregister/confirm.html
{% extends "imapp/base.html" %}
{% block title %} {{ equipment.sam }}を{{ mode_name }}に変更 {% endblock title %}

{% block content %}
    <br>
    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-table"></i>{{ mode_name }}に変更
        </div>
        <div class="card-body">
            <h6>以下の備品を{{ mode_name }}に変更します。よろしいですか？</h6>
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <tr>
                        <td>SAM</td>
                        <td>{{ equipment.sam }}</td>
                    </tr>
                    <tr>
                        <td>区分・種類</td>
                        <td>
                            {% if model.desk_or_lap == 'desktop' %}
                                デスクトップPC
                            {% elif model.desk_or_lap == 'laptop' %}
                                ノートPC
                            {% else %}
                                ディスプレイ
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>モデル名</td>
                        <td>{{ model.model_name }}</td>
                    </tr>
                    <tr>
                        <td>メーカー</td>
                        <td>{{ model.maker }}</td>
                    <tr>
                        <td>発売日</td>
                        <td>{{ model.release_date }}
                    </tr>
                    <tr>
                        <td>購入日</td>
                        <td>{{ equipment.purchase }}</td>
                    </tr>
                        <td>保証期限</td>
                        <td>{{ equipment.warranty }}</td>
                    <tr>
                        <td>備考</td>
                        <td>{{ equipment.note }}</td>
                    </tr>
                </table>
            </div>
            <form action="{% url 'imapp:unregister_run' mode_id %}" method="post">
                {% csrf_token %}
                <div class="col-xs-3" style="max-width: 200px;">
                    <div class="form-group">
                        <div class="col-xs-offset-1 col-xs-10">
                            <input type="submit" class="btn btn-primary" name="ok" value="OK">
                            <input type="hidden" name="sam" value="{{ equipment.sam }}">
                        </div>
                    </div>
                </div>
            </form>
            <form action="{% url 'imapp:unregister_index' mode_id %}" method="get">
                <div class="col-xs-3" style="max-width: 200px;">
                    <div class="form-group">
                        <div class="col-xs-offset-1 col-xs-10">
                            <input type="submit" class="btn btn-danger" name="cancel" value="キャンセル">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

im_site/imapp/templates/imapp/unregister/index.html
{% extends "imapp/base.html" %}
{% block title %} {{ mode_name }}に変更 {% endblock title %}

{% block content %}

    {% if changed %}
        <li class="alert alert-success">
            {{ changed }}を{{ mode_name }}に変更しました。
        </li>
    {% endif %}

    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-table"></i> {{ mode_name }}に変更
        </div>
        <div class="card-body">
            <h6>{{ mode_name }}にする備品のSAMを選択してください。</h6>
            <form action="{% url 'imapp:unregister_confirm' mode_id %}" method="post">
                {% csrf_token %}
                <div class="col-xs-3" style="max-width: 200px;">
                    <div class="form-group">
                        <div class="col-xs-3">
                            <select class="form-control" id="sam" name="sam">
                                <option value="divider" disabled>--- デスクトップPC ---</option>
                                {% for sam in sams_of_desktop %}
                                    <option value="{{ sam }}">{{ sam }}</option>
                                {% endfor %}
                                <option value="divider" disabled>--- ノートPC ---</option>
                                {% for sam in sams_of_laptop %}
                                    <option value="{{ sam }}">{{ sam }}</option>
                                {% endfor %}
                                <option value="divider" disabled>--- ディスプレイ ---</option>
                                {% for sam in sams_of_display %}
                                    <option value="{{ sam }}">{{ sam }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-offset-1 col-xs-10">
                            <input type="submit" class="btn btn-danger" name="mode_name" value="{{ mode_name }}に変更">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

im_site/imapp/templates/imapp/unregister/no_sam.html
{% extends "imapp/base.html" %}
{% block title %} {{ mode_name }}に変更 {% endblock title %}

{% block content %}

    {% if changed %}
        <li class="alert alert-success">
            {{ changed }}を{{ mode_name }}に変更しました。
        </li>
    {% endif %}

    <h6>選択できるSAMがありません。</h6>

{% endblock %}