im_site/im_site/urls.py
from django.conf import settings
from django.conf.urls.static import static

"""im_site URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView


urlpatterns = [
    path('favicon.ico',RedirectView.as_view(url=settings.STATIC_URL + 'favicon.ico')),
    path('imapp/', include('imapp.urls')),
    path('admin/',admin.site.urls ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

im_site/imapp/urls.py
from django.urls import path
from . import views

app_name = 'imapp'
urlpatterns = [
    # ex: /imapp/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /imapp/register, /imapp/deregister ...
    path('register/', views.register.as_view(), name='register'),
    path('log/', views.LogView.as_view(), name='log'),
    path('sclog/', views.scLogView.as_view(), name='sclog'),
    # ex: /imapp/log/D01/
    path('log/<str:sam_site>/', views.loglog, name='loglog'),
    # unregister
    path('unregister/index/<int:mode_id>/', views.UnregisterIndexView.as_view(), name='unregister_index'),
    path('unregister/confirm/<int:mode_id>/', views.UnregisterConfirmView.as_view(), name='unregister_confirm'),
    path('unregister/run/<int:mode_id>', views.run_unregister, name='unregister_run'),
]

im_site/imapp/models.py
import datetime

from django.db import models
from django.utils import timezone
from django import forms


class ModelInfo(models.Model):
    model_id = models.AutoField('モデルID',
                                primary_key=True)
    pc_or_display = models.CharField(
        '区分', max_length=100, choices=(('pc', 'PC'), ('display', 'ディスプレイ'),))
    desk_or_lap = models.CharField('種類', max_length=100,
                                   choices=(('desktop', 'デスクトップPC'), ('laptop', 'ノートPC'),), null=True)
    model_name = models.CharField('モデル名', max_length=100)
    maker = models.CharField('メーカー', max_length=100)
    release_date = models.DateField('発売日')

    class Meta:
        unique_together = ('pc_or_display', 'model_name',
                           'maker', 'release_date',)
        verbose_name = "モデル"  # model-name on admin/imapp/$MODEL
        verbose_name_plural = "モデル"  # model-name on admin/imapp

    def __str__(self):
        return str(self.model_name)


class DisplayInfo(models.Model):
    model_id = models.OneToOneField(
        ModelInfo,
        related_name="related_model_id",
        on_delete=models.CASCADE, primary_key=True)
    inch = models.FloatField('インチ', default=24.0)

    class Meta:
        verbose_name = "ディスプレイ情報"
        verbose_name_plural = "ディスプレイ情報"

    def __str__(self):
        return str(self.inch)


class Equipment(models.Model):
    sam = models.CharField('SAM', max_length=100, primary_key=True)
    pc_or_display = models.CharField('区分', max_length=100, choices=(
        ('pc', 'PC'),
        ('display', 'ディスプレイ'),))
    purchase = models.DateField('購入日')
    warranty = models.DateField('保証期限')
    note = models.TextField('備考', blank=True)
    model_id = models.ForeignKey(ModelInfo, on_delete=models.PROTECT)

    class Meta:
        verbose_name = "備品 (PC)"
        verbose_name_plural = "備品 (PC)"

    def __str__(self):
        return str(self.sam)


class OsId(models.Model):
    os_id = models.AutoField('OSID', primary_key=True)
    os = models.CharField('OS', max_length=100, unique=True)

    class Meta:
        verbose_name = "OS"
        verbose_name_plural = "OS"

    def __str__(self):
        return str(self.os)


class CpuId(models.Model):
    cpu_id = models.AutoField('CPU',
                              primary_key=True)
    cpu = models.CharField('CPU', max_length=100, unique=True)

    class Meta:
        verbose_name = "CPU"
        verbose_name_plural = "CPU"

    def __str__(self):
        return str(self.cpu)


class DriveId(models.Model):
    drive_id = models.AutoField('ドライブID', primary_key=True)
    drive = models.CharField('ドライブ', max_length=100, unique=True)

    class Meta:
        verbose_name = "ドライブ"
        verbose_name_plural = "ドライブ"

    def __str__(self):
        return str(self.drive)

class MemoryId(models.Model):
    memory_id = models.AutoField('メモリID', primary_key=True)
    memory = models.CharField('メモリ', max_length=100, unique=True)

    class Meta:
        verbose_name = "メモリ"
        verbose_name_plural = "メモリ"

    def __str__(self):
        return str(self.memory)

class PcEquipment(models.Model):
    sam = models.OneToOneField(
        Equipment,
        related_name="related_sam_id",
        on_delete=models.CASCADE, primary_key=True)
    os_id = models.ForeignKey(OsId, on_delete=models.PROTECT)
    cpu_id = models.ForeignKey(CpuId,
                               on_delete=models.PROTECT)
    drive_id = models.ForeignKey(DriveId, on_delete=models.PROTECT)
    memory_id = models.ForeignKey(MemoryId, on_delete=models.PROTECT)

    class Meta:
        verbose_name = "PC備品"
        verbose_name_plural = "PC備品"

    def __str__(self):
        return str(self.sam)


class User(models.Model):
    YEAR_CHOICES = []
    for r in range(2006, (datetime.datetime.now().year+1)):
        YEAR_CHOICES.append((r, r))
    YEAR_CHOICES.sort(reverse=True)
    user_id = models.AutoField('利用者ID', primary_key=True)
    username = models.CharField('利用者名', max_length=100)
    assigned_year = models.IntegerField(
        '配属年度', choices=YEAR_CHOICES, default=datetime.datetime.now().year)
    is_affiliated = models.BooleanField('現役？', default=True)

    class Meta:
        unique_together = ('username', 'assigned_year',)
        verbose_name = "利用者"
        verbose_name_plural = "利用者"

    def judge_affiliation(self):
        return self.is_affiliated

    judge_affiliation.admin_order_field = 'is_affiliated'
    judge_affiliation.boolean = True
    judge_affiliation.short_description = "現役?????"

    def __str__(self):
        return str(self.username) + " (" + str(self.assigned_year) + "年配属) "


class Log(models.Model):
    """
    'id' is automatically made and set as a primary key.
    """
    sam = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    begin_date = models.DateField('使用開始日')
    user_id = models.ForeignKey(User,
                                on_delete=models.CASCADE)

    class Meta:
        unique_together = ('sam', 'begin_date', 'user_id',)
        verbose_name = "ログ"
        verbose_name_plural = "ログ ⚠基本的に使用しないこと⚠"

    def __str__(self):
        return "(" + str(self.sam) + ", " + str(self.user_id.username) + ", " + str(self.begin_date) + ")"

im_site/imapp/forms.py
from django import forms

im_site/imapp/views.py
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from .models import ModelInfo, Equipment, User, PcEquipment, Log
from django.db import connection
from django.template import loader
from collections import defaultdict
from datetime import datetime
from django.shortcuts import render, redirect
from django.http import Http404
from django.urls import reverse

NOT_ASSIGNED_ID = 1
TO_BE_SCRAPPED_ID = 2
SCRAPPED_ID = 3

ID_MODE = {NOT_ASSIGNED_ID, TO_BE_SCRAPPED_ID, SCRAPPED_ID}


class RegisterBaseInfo:
    def __init__(self, username, userid, year, desktop, laptop, displays):
        self.username = username
        self.userid = userid
        self.assignedyear = year
        self.desktop = desktop
        self.laptop = laptop
        self.displays = displays

    def __str__(self):
        return "in RegisterBaseInfo class(debug on __str__): " + str(self.username) + ", " + str(
            self.userid) + ", " + str(self.desktop) + ", " + str(self.laptop) + ", " + str(self.displays)


class register(generic.ListView):
    """
    in registering user&sam to log
    """
    template_name = 'imapp/register.html'

    NO_DEFAULT_SAM = "該当なし"
    DISPOSAL_ID = [TO_BE_SCRAPPED_ID, SCRAPPED_ID]  # disposal or will dispose
    # not assigned or disposal or will dispose
    NO_USE_ID = [NOT_ASSIGNED_ID, TO_BE_SCRAPPED_ID, SCRAPPED_ID]

    def __init__(self):
        self.SendContentsSave = []

    def GetValidSamAndUsersSam(self, SendContents, DesktopSamTable, LaptopSamTable, DisplaySamTable):
        """
        Requirement: A and B don't exist such as A.sam == B.sum ∧ A.begin_date == B.begin_date is in LOG
        {users}, {user-desktop-sam, {vaild-desktop-sam}}, 
        {user-laptop-sam, {vaild-laptop-sam}}, {user-displaysam1/2, {valid-display-sam}}

        """
        cursor = connection.cursor()
        cursor.execute("""SELECT sam_id,user_id_id FROM (SELECT A.sam_id, 
        A.user_id_id FROM imapp_log AS A INNER JOIN 
        (SELECT sam_id, MAX(begin_date) AS MaxDate 
        FROM `imapp_log` GROUP BY sam_id) AS B
        ON A.sam_id = B.sam_id AND A.begin_date = B.MaxDate ) as C 
        INNER JOIN imapp_user ON C.user_id_id = imapp_user.user_id""")
        sam_userid_rows = cursor.fetchall()

        # No valid ID
        NoValidSumTable = []
        userid_sam_dfdict = defaultdict(list)
        for sam, userid in sam_userid_rows:
            if userid not in self.DISPOSAL_ID:
                userid_sam_dfdict[userid].append(sam)
            else:
                NoValidSumTable.append(sam)

        # display valid ID
        DisplaySamTable.clear()

        for dic in Equipment.objects.all().filter(pc_or_display="display").values():
            if dic["sam"] not in NoValidSumTable:
                DisplaySamTable.append(dic["sam"])
        DisplaySamTable.append(self.NO_DEFAULT_SAM)

        # Desktop valid ID
        DesktopSamTable.clear()

        desktop_dicts = ModelInfo.objects.all().filter(desk_or_lap="desktop").values()
        desktop_model_ids = [id_dict['model_id'] for id_dict in desktop_dicts]

        for equip in Equipment.objects.all().values():
            if equip["model_id_id"] in desktop_model_ids:
                if equip["sam"] not in NoValidSumTable:
                    DesktopSamTable.append(equip["sam"])
        DesktopSamTable.append(self.NO_DEFAULT_SAM)

        # Laptop valid ID
        LaptopSamTable.clear()

        laptop_dicts = ModelInfo.objects.all().filter(desk_or_lap="laptop").values()
        laptop_model_ids = [id_dict['model_id'] for id_dict in laptop_dicts]

        for equip in Equipment.objects.all().values():
            if equip["model_id_id"] in laptop_model_ids:
                if equip["sam"] not in NoValidSumTable:
                    LaptopSamTable.append(equip["sam"])
        LaptopSamTable.append(self.NO_DEFAULT_SAM)

        userid_sam_dict = dict(userid_sam_dfdict)  # defaultdict to dict

        SendContents.clear()
        for userdata in User.objects.all().values():
            username = userdata["username"]
            userid = userdata["user_id"]
            user_assignedyeser = userdata["assigned_year"]
            if userid in self.NO_USE_ID:
                continue
            if userdata["is_affiliated"] == False:
                continue

            UserSamSet = []
            if userid in userid_sam_dict.keys():
                UserSamSet = userid_sam_dict[userid]

            desktopsam = ""  # if cond assignment
            laptopsam = ""
            displaysams = []
            for sam in UserSamSet:
                if sam in DesktopSamTable:
                    desktopsam = sam
                elif sam in LaptopSamTable:
                    laptopsam = sam
                elif sam in DisplaySamTable:
                    displaysams.append(sam)

            # if a person doesn't have sam -> person.sth.sam=NO_DEFAULT_SAM
            if len(desktopsam) < 1:
                desktopsam = self.NO_DEFAULT_SAM
            if len(laptopsam) < 1:
                laptopsam = self.NO_DEFAULT_SAM
            for i in range(2 - len(displaysams)):
                displaysams.append(self.NO_DEFAULT_SAM)
            SendContents.append(RegisterBaseInfo(
                username, userid, user_assignedyeser, desktopsam, laptopsam, displaysams))

    def validsetting(self):
        pass

    def post(self, request, *args, **kwargs):

        post_data = request.POST

        post_id = int(post_data["userid"])
        d =  post_data["desktop-pulldown"]
        l =  post_data["laptop-pulldown"]
        d1 = post_data["display1-pulldown"]
        d2 = post_data["display2-pulldown"]


        # get pre information
        SendContents = []
        DesktopSamTable = []
        LapTopSamTable = []
        DisplaySamTable = []
        self.GetValidSamAndUsersSam(SendContents, DesktopSamTable,
                              LapTopSamTable, DisplaySamTable)


        # get who change sam
        postinfo = RegisterBaseInfo("", post_id, 0, d, l, [d1, d2])
        preinfo = postinfo
        for pre in SendContents:
            if pre.userid == post_id:
                preinfo = pre

        # get pre/change infomation ↓
        predisp1 = preinfo.displays[0]
        predisp2 = preinfo.displays[1]

        # desktop
        class OldAndNew():
            def __init__(self, oldsam, newsam):
                self.newsam = newsam
                self.oldsam = oldsam

        checksams = []
        if preinfo.desktop != postinfo.desktop:
            checksams.append(OldAndNew(preinfo.desktop, postinfo.desktop))

        # laptop
        if preinfo.laptop != postinfo.laptop:
            checksams.append(OldAndNew(preinfo.laptop, postinfo.laptop))

        # display: 2displays -> check algorithm
        deletelist_old = []
        deletelist_new = []
        boolenlist_old = [False for a in preinfo.displays]
        boolenlist_new = [False for a in postinfo.displays]
        for i, newsam in enumerate(postinfo.displays):
            for j, oldsam in enumerate(preinfo.displays):
                if boolenlist_new[i] == False and boolenlist_old[j] == False and newsam == oldsam:
                    deletelist_old.append(oldsam)
                    deletelist_new.append(newsam)
                    boolenlist_old[j] = True
                    boolenlist_new[i] = True

        for oldsam in deletelist_old:
            preinfo.displays.remove(oldsam)
        for newsam in deletelist_new:
            postinfo.displays.remove(newsam)

        assert len(postinfo.displays) == len(
            preinfo.displays), "the size of preinfo.displays is not postinfo.displays, ><"
        for (oldsam, newsam) in zip(preinfo.displays, postinfo.displays):
            checksams.append(OldAndNew(oldsam, newsam))


        """
        old sam -> no_assinnment
        new sam -> person
        """
        ## old sam to LOG
        # if same sam and begin_date in LOG, delete it
        for obj in checksams:
            oldsam = obj.oldsam
            Logsset = Log.objects.all().filter(sam=oldsam, begin_date=datetime.now())
            # if nothing is target, none happens
            Logsset.delete()

        for obj in checksams:
            if obj.oldsam == self.NO_DEFAULT_SAM:
                continue
            insert_query = Log(
                sam=Equipment.objects.get(sam=obj.oldsam),
                begin_date=datetime.now(),
                user_id=User.objects.get(user_id=NOT_ASSIGNED_ID)
            )
            insert_query.save()


        # delete same date and sam
        for obj in checksams:
            if obj.newsam == self.NO_DEFAULT_SAM:
                continue
            newsam = obj.newsam
            Logsset = Log.objects.all().filter(sam=newsam, begin_date=datetime.now())
            Logsset.delete() # if nothing is target, none happens

        # new data to LOG
        for obj in checksams:
            if obj.newsam == self.NO_DEFAULT_SAM:
                continue
            insert_query = Log(
                sam=Equipment.objects.get(sam=obj.newsam),
                begin_date=datetime.now(),
                user_id=User.objects.get(user_id=postinfo.userid)
            )
            insert_query.save()

        class SamChangeInfo:  # insert only diff data
            def __init__(self, id, de, l, d1, d2, change=False, deskch=False, lapch=False, dispch=False):
                self.id = id
                self.desktop = de
                self.laptop = l
                self.display = [d1, d2]
                self.change = change
                self.desktopchange = deskch
                self.laptopchange = lapch
                self.displaychange = dispch

        # diff check(worst...)
        cnt = 0
        chflag = False
        deskflag = False
        lapflag = False
        dispflag = False
        if preinfo.desktop == postinfo.desktop:
            cnt += 1
        else:
            deskflag = True

im_site/imapp/templates/imapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <title>{% block title %}{% endblock title %}</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <!--<link rel="icon" href="{% static 'favicon.ico' %}"/>-->
</head>



<body class="fixed-nav sticky-footer bg-dark" id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <a class="navbar-brand" href="{% url 'imapp:index' %}"> <img src="{% static 'img/transparent_all.png' %}" alt="logo"> Ishikawa Lab. Machine Manegement System</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="ログ閲覧">
                    <a class="nav-link" href="{% url 'imapp:log' %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">ログ閲覧</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="利用登録・修正">
                    <a class="nav-link" href="{% url 'imapp:register' %}">
                        <i class="fa fa-fw fa-desktop"></i>
                        <span class="nav-link-text">利用登録・修正</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="未割当に変更">
                    <a class="nav-link" href="{% url 'imapp:unregister_index' 1 %}">
                        <i class="fa fa-fw fa-user-times"></i>
                        <span class="nav-link-text">未割当に変更</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="廃棄予定に変更">
                    <a class="nav-link" href="{% url 'imapp:unregister_index' 2 %}">
                        <i class="fa fa-fw fa-minus-circle"></i>
                        <span class="nav-link-text">廃棄予定に変更</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="廃棄に変更">
                    <a class="nav-link" href="{% url 'imapp:unregister_index' 3 %}">
                        <i class="fa fa-fw fa-trash"></i>
                        <span class="nav-link-text">廃棄に変更</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="管理画面">
                    <a class="nav-link" href="{% url 'admin:index' %}">
                        <i class="fa fa-fw fa-wrench"></i>
                        <span class="nav-link-text">管理画面</span>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav sidenav-toggler">
                <li class="nav-item">
                    <a class="nav-link text-center" id="sidenavToggler">
                        <i class="fa fa-fw fa-angle-left"></i>
                    </a>
                </li>
            </ul>

        </div>
    </nav>
    <div class="content-wrapper">
        <div class="container-fluid">

            {% block content %}
            {% endblock %}

        </div>
        <!-- /.container-fluid-->
        <!-- /.content-wrapper-->
        <footer class="sticky-footer">
            <div class="container">
                <div class="text-center">
                    <small>Copyright © Ishikawa Lab. since 2006</small>
                </div>
            </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fa fa-angle-up"></i>
        </a>

        <!-- Bootstrap core JavaScript-->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <!-- Core plugin JavaSc'ript-->
        <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
        <!-- Page level plugin 'JavaScript-->
        <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
        <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
        <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>
        <!-- Custom scripts for' all pages-->
        <script src="{% static 'js/sb-admin.min.js' %}"></script>
        <!-- Custom scripts for' this page-->
        <script src="{% static 'js/sb-admin-datatables.js' %}"></script>
        <!--<script src="{% static 'js/sb-admin-datatables.min.js' %}"></script>-->
        <script src="{% static 'js/sb-admin-charts.min.js' %}"></script>
    </div>
</body>
</html>

im_site/imapp/templates/imapp/index.html
{% extends "imapp/base.html"%}
{% block title %} ようこそ iManage へ {% endblock %}

{% block content %}

<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Top
    </div>
    <div class="card-body">
        <!-- Icon Cards-->
        <div class="row">
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-primary o-hidden h-100">
                    <div class="card-body">
                        <div class="card-body-icon">
                            <i class="fa fa-fw fa-comments"></i>
                        </div>
                        <div class="mr-5">ログ閲覧</div>
                    </div>
                    <a class="card-footer text-white clearfix small z-1" href="{% url 'imapp:log' %}">
                        <span class="float-left">View logs</span>
                        <span class="float-right">
                            <i class="fa fa-angle-right"></i>
                        </span>
                    </a>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-warning o-hidden h-100">
                    <div class="card-body">
                        <div class="card-body-icon">
                            <i class="fa fa-fw fa-list"></i>
                        </div>
                        <div class="mr-5">利用登録・修正</div>
                    </div>
                    <a class="card-footer text-white clearfix small z-1" href="{% url 'imapp:register' %}">
                        <span class="float-left">Register and adjust</span>
                        <span class="float-right">
                            <i class="fa fa-angle-right"></i>
                        </span>
                    </a>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-success o-hidden h-100">
                    <div class="card-body">
                        <div class="card-body-icon">
                            <i class="fa fa-fw fa-shopping-cart"></i>
                        </div>
                        <div class="mr-5">未割当に変更</div>
                    </div>
                    <a class="card-footer text-white clearfix small z-1" href="{% url 'imapp:unregister_index' 1 %}">
                        <span class="float-left">Cancel assignment</span>
                        <span class="float-right">
                            <i class="fa fa-angle-right"></i>
                        </span>
                    </a>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-danger o-hidden h-100">
                    <div class="card-body">
                        <div class="card-body-icon">
                            <i class="fa fa-fw fa-support"></i>
                        </div>
                        <div class="mr-5">廃棄済に変更</div>
                    </div>
                    <a class="card-footer text-white clearfix small z-1" href="{% url 'imapp:unregister_index' 3 %}">
                        <span class="float-left">Mark as scrapped</span>
                        <span class="float-right">
                            <i class="fa fa-angle-right"></i>
                        </span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

im_site/imapp/templates/imapp/loglog.html
<!--  ここで SAM to USER の Log を出す用のtemplateをかく-->
{% extends "imapp/base.html"%}
{% block title %} LOGLOGだよ {% endblock %}

{% block content %}
<!-- Example DataTables Card-->
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> {% if sam_site %} {{ sam_site }}の過去のログ一覧 {% endif %}
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th> 利用者 </th>
                        <th> 利用開始日 </th>
                    </tr>
                </thead>

                {% if date_user_rows %}
                <tbody>
                    {% for data in date_user_rows %}
                    <tr>
                        <td>{{ data.1 }}</td>
                        <td>{{ data.0 }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
                {% else %}
                <p>No log are available.</p>
                {% endif %}
            </table>
        </div>
    </div>
</div>

{% endblock %}